inputSet:
  name: Build_maven_web_application_1694503450384-push-trigger-input-set
  identifier: Build_maven_web_application_1694503450384pushtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_maven_web_application_1694503450384
    properties:
      ci:
        codebase:
          build:
            type: branch
            spec:
              branch: <+trigger.branch>
