inputSet:
  name: Build_maven_web_application_1694503450384-pr-trigger-input-set
  identifier: Build_maven_web_application_1694503450384prtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_maven_web_application_1694503450384
    properties:
      ci:
        codebase:
          build:
            type: PR
            spec:
              number: <+trigger.prNumber>
